services:
  - type: web
    name: dcam-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        value: "your-mongodb-connection-string"
      - key: PYTHON_VERSION
        value: "3.11.0"